---
title: "Euan Analysis"
output: html_notebook
---
```{r}
library(plotly)
library(e1071)
```


```{r}
source(file = "cleaning.R")
```



```{r}
inputs <- list(
  admission_input = "Emergency Inpatients",
  sex_input = "Male",
  age_input = "40-49 years",
  simd_input = 5,
  age_sex = "age",
  lockdown_input = "post"
  
  
)
```





```{r}

bot_simd_clean %>% 
  filter(admission_type == inputs$admission_input) %>% 
  group_by(simd) %>% 
  summarise(total_episodes = sum(episodes)) %>% 
  ggplot()+
  aes(x = simd,
      y = total_episodes,
      fill = as.factor(simd)) +
  geom_col() +
  theme_minimal()+
  labs(
    x = "SIMD Level",
    y = "Total Episodes"
  ) +
  theme(
    legend.position = "none"
  )
```

```{r}
bot_sex_clean %>% 
  group_by(age,
           sex) %>% 
  summarise(total_episodes = sum(episodes)) %>% 
  ggplot()+
  aes(x = age,
      y = total_episodes,
      fill = sex) +
  geom_col(position = "dodge") +
  theme_minimal()+
  labs(
    x = "\nAge Ranges",
    y = "Total Episodes\n"
  ) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 315,
                               vjust = 0.2,
                               hjust = 0.5)
  )


```


```{r}
bot_sex_clean %>% 
  filter(age == inputs$age_input,
         admission_type %in% c("Elective Inpatients",
                               "Emergency Inpatients")) %>% 
  group_by(age, admission_type) %>% 
  summarise(tot_episodes = sum(episodes)) %>% 
  ggplot()+
  aes(x = age,
      y = tot_episodes,
      fill = admission_type) +
  geom_col(position = "dodge")
```



```{r}
simd_stack <- ggplotly(bot_simd_clean %>% 
  drop_na(simd) %>% 
  filter(admission_type %in% c("Elective Inpatients",
                               "Emergency Inpatients"),
         lockdown == inputs$lockdown_input) %>% 
  group_by(simd, admission_type) %>% 
  summarise(total_episodes = sum(episodes)) %>% 
  ggplot()+
  aes(x = simd,
      y = total_episodes,
      fill = admission_type) +
  geom_col(position = "stack")+
  theme_minimal(
  ) +
  labs(
    x = "\nSIMD Ranking",
    y = "Total Episodes\n",
    fill = "Admission Type"
  ))
```

```{r}
bot_sex_clean %>% 
  group_by(sex, quarter) %>% 
  summarise(mean_episodes = mean(episodes)) %>% 
  ggplot() +
  aes(x = quarter,
      y = mean_episodes,
      group = sex,
      colour = sex) +
  geom_line() +
  theme(
    axis.text.x = element_text(angle = 315,
                               vjust = 0.2,
                               hjust = 0.5)
  
    )
  
  
``` 

```{r}
bot_simd_clean %>% 
  drop_na(simd) %>% 
  filter(admission_type %in% c("Elective Inpatients",
                               "Emergency Inpatients")) %>% 
  group_by(simd, admission_type) %>% 
  summarise(mean_episodes = mean(episodes)) %>% 
  ggplot()+
  aes(x = simd,
      y = mean_episodes,
      fill = admission_type) +
  geom_col(position = "stack")
```


```{r}
bot_simd_clean %>% 
  drop_na(simd) %>% 
  filter(admission_type %in% c("Elective Inpatients",
                               "Emergency Inpatients")) %>% 
  group_by(simd, admission_type) %>% 
  summarise(mean_episodes = sum(episodes))
```


```{r}
ggplotly(covid_simd %>% 

  ggplot() +
    aes(
      x = simd_quintile,
      y = first_infections,
      fill = as.factor(simd_quintile),
      text = first_infections
    ) +
    geom_col()
)
```



```{r}
ggplotly(covid_simd %>% 

  ggplot() +
    aes(
      x = simd_quintile,
      y = reinfections,
      text = reinfections
    ) +
    geom_col(fill = "blue") +
    theme_minimal(),
  tooltip = "text"
)
```


```{r}
bot_sex_clean %>% 
  filter(age == "0-9 years") %>% 
  group_by(sex) 
```




```{r}
bot_sex_clean %>%
  mutate(age = case_when(
    age == "0-9 years" ~ "4.5",
    age == "10-19 years" ~ "14.5",
    age == "20-29 years" ~ "24.5",
    age == "30-39 years" ~ "34.5",
    age == "40-49 years" ~ "44.5",
    age == "50-59 years" ~ "54.5",
    age == "60-69 years" ~ "64.5",
    age == "70-79 years" ~ "74.5",
    age == "80-89 years" ~ "84.5",
    age == "90 years and over" ~ "94.5"
  )) %>% 
  mutate(age = as.numeric(age)) %>%
  group_by(age) %>% 
  summarise(total_eps = sum(episodes)) %>% 
  ggplot() +
  aes(x = age,
      y = total_eps) +
  geom_col() +
  geom_smooth(method = "loess",
              se = TRUE,
              colour = "red") +
  theme_minimal()
```



```{r}
bot_sex_clean %>%
  mutate(age = case_when(
    age == "0-9 years" ~ "4.5",
    age == "10-19 years" ~ "14.5",
    age == "20-29 years" ~ "24.5",
    age == "30-39 years" ~ "34.5",
    age == "40-49 years" ~ "44.5",
    age == "50-59 years" ~ "54.5",
    age == "60-69 years" ~ "64.5",
    age == "70-79 years" ~ "74.5",
    age == "80-89 years" ~ "84.5",
    age == "90 years and over" ~ "94.5"
  )) %>% 
  mutate(age = as.numeric(age)) %>%
  group_by(age) %>% 
  summarise(total_eps = sum(episodes)) %>% 
  mutate(count = total_eps) %>% 
  select(-total_eps) %>% 
  summarise(skewness = skewness(count))
```



