---
title: "R Notebook"
output: html_notebook
---

# Shiny Dashboard - Data Cleaning and Visualisations

## Bed Occupancy

```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(stringr)
library(sf)
library(rgdal)
library(leaflet)

beds <- read_csv("raw_data/by_board_of_treatment/beds_by_nhs_board_of_treatment_and_specialty.csv")

hospital_codes <- read_csv("raw_data/codes/hospital_codes.csv")

board_codes <- read_csv("raw_data/codes/health_board_codes.csv")

beds
```
```{r}
hospital_codes_clean <- hospital_codes %>%
  clean_names() %>% 
  select(location, hb, x_coordinate, y_coordinate)

board_codes_clean <- board_codes %>% 
  clean_names() %>% 
  select(hb, hb_name)

health_boards <- inner_join(hospital_codes_clean, board_codes_clean, by = "hb")
```

```{r}
beds_clean <- beds %>% 
  select(- c("PercentageOccupancyQF",
         "AverageOccupiedBedsQF",
         "AverageAvailableStaffedBedsQF",
         "TotalOccupiedBeddaysQF",
         "AllStaffedBeddaysQF",
         "SpecialtyNameQF",
         "SpecialtyQF", 
         "LocationQF",
         "HBQF",
         "QuarterQF",
         "Specialty")) %>% 
  clean_names() %>%
  mutate(quarter = str_replace(quarter, "Q1", "-01-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q2", "-04-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q3", "-07-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q4", "-10-01")) %>% 
  mutate(quarter = ymd(quarter)) %>% 
  inner_join(health_boards, by = "location") %>% 
  select(- c("hb.x", "hb.y")) %>% 
  mutate(hb_name = gsub("NHS ", "", hb_name))
```

```{r}
beds_clean %>% 
  arrange(percentage_occupancy)
```


## A&E wait times

```{r}
ae_times <- read_csv("raw_data/by_board_of_treatment/monthly_ae_waitingtimes_202301.csv")

ae_times_clean <- ae_times %>% 
  select(- c("AttendanceGreater12hrsQF", "AttendanceGreater8hrsQF", "DischargeDestinationUnknownQF", "DischargeDestinationTransferQF", "DischargeDestinationResidenceQF", "DischargeDestinationOtherSpecialtyQF", "DischargeDestinationAdmissionToSameQF", "NumberMeetingTargetEpisodeQF", "NumberOfAttendancesEpisodeQF")) %>%
  clean_names() %>% 
  rename(hb = hbt) %>% 
  rename(location = treatment_location) %>% 
  inner_join(health_boards, by = "location") %>% 
  select(- c("hb.x", "hb.y")) %>% 
  mutate(month = ym(month)) %>% 
  rename(date = month) %>% 
  filter(date > "2018-01-01") %>% 
  mutate(percentage_meeting_target = (number_meeting_target_aggregate/number_of_attendances_aggregate)*100)
  
```

## Demographics by treatment board

```{r}
treatment_age_sex <- read_csv("raw_data/by_board_of_treatment/inpatient_and_daycase_by_nhs_board_of_treatment_age_and_sex.csv")

treatment_age_sex_clean <- treatment_age_sex %>% 
  select(- c("QuarterQF", "HBQF", "LocationQF", "AdmissionTypeQF", "AverageLengthOfEpisodeQF", "AverageLengthOfStayQF")) %>% 
  clean_names() %>% 
  mutate(quarter = str_replace(quarter, "Q1", "-01-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q2", "-04-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q3", "-07-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q4", "-10-01")) %>% 
  mutate(quarter = ymd(quarter)) %>% 
  pivot_longer(cols = c("sex", "age"),
               names_to = "demographic",
               values_to = "value")
  
```

```{r}
treatment_simd <- read_csv("raw_data/by_board_of_treatment/inpatient_and_daycase_by_nhs_board_of_treatment_and_simd.csv")

treatment_simd_clean <- treatment_simd %>% 
  select(- c("QuarterQF", "HBQF", "LocationQF", "AdmissionTypeQF", "AverageLengthOfEpisodeQF", "AverageLengthOfStayQF", "SIMDQF")) %>% 
  clean_names() %>% 
  mutate(quarter = str_replace(quarter, "Q1", "-01-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q2", "-04-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q3", "-07-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q4", "-10-01")) %>% 
  mutate(quarter = ymd(quarter)) %>% 
  pivot_longer(cols = simd,
               names_to = "demographic",
               values_to = "value") %>% 
  mutate(value = as.character(value))
```

```{r}
treatment_specialty <- read_csv("raw_data/by_board_of_treatment/inpatient_and_daycase_by_nhs_board_of_treatment_and_specialty.csv")

treatment_specialty_clean <- treatment_specialty %>% 
  select(- c("QuarterQF", "HBQF", "LocationQF", "AdmissionTypeQF", "AverageLengthOfEpisodeQF", "AverageLengthOfSpellQF", "Specialty")) %>% 
  clean_names() %>% 
  rename(stays = spells) %>% 
  rename(length_of_stay = length_of_spell) %>% 
  rename(average_length_of_stay = average_length_of_spell) %>%
  rename(specialty = specialty_name) %>% 
  mutate(quarter = str_replace(quarter, "Q1", "-01-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q2", "-04-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q3", "-07-01")) %>% 
  mutate(quarter = str_replace(quarter, "Q4", "-10-01")) %>% 
  mutate(quarter = ymd(quarter)) %>% 
    pivot_longer(cols = specialty,
               names_to = "demographic",
               values_to = "value")
```

```{r}
binded_data_1 <- bind_rows(treatment_age_sex_clean, treatment_simd_clean)

covid_by_treatment_board <- bind_rows(binded_data_1, treatment_specialty_clean)
```

# Visualisations for dashboard

```{r}
ae_times_clean %>% 
  filter(date > "2020-01-01")

beds_clean
```


```{r}
beds_clean %>% 
  select(quarter, specialty_name, hb_name, percentage_occupancy) %>% 
  filter(specialty_name == "All Specialties") %>% 
  group_by(hb_name, quarter) %>%
  summarise(average_occupancy = mean(percentage_occupancy)) %>% 
  ggplot() +
    aes(x = quarter, y = average_occupancy, colour = hb_name) +
    geom_line() +
    scale_colour_manual(values = c("yellow1", "darkorchid4", "burlywood3", "firebrick4", "forestgreen", "hotpink", "darkorange3",  "palegreen2", "cadetblue2", "orchid3", "black", "navy", "antiquewhite4", "sienna2")) +
  labs(x = "Date",
       y = "Average Bed Occupancy",
       colour = "Healthboard") +
  theme_classic()
  
```

```{r}
ae_times_clean %>%
  select(hb_name, date, number_of_attendances_aggregate) %>% 
  group_by(hb_name, date) %>%
  summarise(total_attendances = sum(number_of_attendances_aggregate)) %>% 
  ggplot() +
    aes(x = date, y = log(total_attendances), colour = hb_name) +
    geom_line() +
  scale_colour_manual(values = c("yellow1", "darkorchid4", "burlywood3", "firebrick4", "forestgreen", "hotpink", "darkorange3",  "palegreen2", "cadetblue2", "orchid3", "black", "navy", "antiquewhite4", "sienna2")) +
  labs(x = "Date",
       y = "A&E Attendances (log scaled)",
       colour = "Healthboard") +
  theme_classic()
```

```{r}
scotland_hb <- clean_names(st_read("raw_data/health_board_mapping/SG_NHS_HealthBoards_2019/SG_NHS_HealthBoards_2019.shp"))

scotland_hb_xform <- st_transform(scotland_hb, 4326) %>% 
  st_simplify(dTolerance = 1000)

```

```{r}
getcolour <- function(d) {
  case_when(
    d >= 95 ~ "#000000",
    d >= 90 ~ "#330000",
    d >= 85 ~ "#4d0000",
    d >= 80 ~ "#660000",
    d >= 75 ~ "#800000",
    d >= 70 ~ "#990000",
    d >= 65 ~ "#b30000",
    d >= 60 ~ "#cc0000",
    d >= 55 ~ "#e60000",
    d >= 50 ~ "#ff0000",
    d >= 45 ~ "#ff1a1a",
    d >= 40 ~ "#ff3333",
    d >= 35 ~ "#ff4d4d",
    d >= 30 ~ "#ff6666",
    d >= 25 ~ "#ff8080",
    d >= 20 ~ "#ff9999",
    d >= 15 ~ "#ffb3b3",
    d >= 10 ~ "#ffcccc",
    d >= 5 ~ "#ffe6e6",
    d < 5 ~ "#ffffff"
    
  )
}
```

```{r}
getcolour(50)
```


```{r}
scotland_hb_xform %>%
  leaflet() %>% 
  addTiles() %>% 
  addPolygons(label = ~hb_name,
              fillColor = getcolour(beds_clean$percentage_occupancy), 
              opacity = 0.8)
  
```


